name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update progress.md
      run: |
        echo "## Daily update - $(date -u)" >> progress.md
        echo "- Placeholder log. Replace with real updates soon." >> progress.md
        echo "" >> progress.md

    - name: Commit and push
      run: |
        git config --global user.name 'HeyNaNd0'
        git config --global user.email '22282823+HeyNaNd0@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/HeyNaNd0/fcc-progress-log.git
        git add progress.md
        git commit -m "Daily progress log update - $(date -u)" || echo "No changes to commit"
        git push
